/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package layout

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$addFeedback_jade {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<html>\n  <head>\n    <title>my jade template</title>\n    <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n    <script type=\"text/javascript\" src=\"/assets/javascripts/addFeedback.js\"></script>\n  </head>\n  <body>\n    <form id=\"addForm\" method=\"POST\" action=\"\">\n      Name:\n      <input type=\"text\" name=\"by\" id=\"by\"/>\n      <br/>\n      Email:\n      <input type=\"email\" name=\"email\" id=\"email\"/>\n      <br/>\n      Topic:\n      <input type=\"text\" name=\"topic\" id=\"topic\"/>\n      <br/>\n      Rating:\n      <input type=\"text\" name=\"rating\" id=\"rating\"/>\n      <br/>\n      Comment:\n      <input type=\"text\" name=\"comment\" id=\"comment\"/>\n      <br/>\n      <br/>\n      <h3 id=\"response\"></h3>\n      <br/>\n      <br/>\n      <input type=\"button\" value=\"ADD\" id=\"addButton\"/>\n      <br/>\n      <input type=\"button\" value=\"Back to main page\" id=\"backButton\"/>\n    </form>\n  </body>\n</html>\n" );
    }
  }
}


class $_scalate_$addFeedback_jade extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$addFeedback_jade.$_scalate_$render(context)
}
