/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package layout

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$search_jade {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<html>\n  <head>\n    <title>my jade template</title>\n    <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n    <script type=\"text/javascript\" src=\"/assets/javascripts/searchFeedback.js\"></script>\n  </head>\n  <body>\n    <form id=\"searchForm\" method=\"POST\" action=\"\">\n      <select name=\"mydropdown\">\n        <option value=\"by\">By</option>\n        <option value=\"topic\">Topic</option>\n        <option value=\"comment\">Comment</option>\n        <option value=\"date\">Date before</option>\n        <option value=\"fullText\">Full text search</option>\n      </select>\n      <input type=\"text\" name=\"input\"/>\n      <br/>\n      <br/>\n      <input type=\"button\" value=\"Search\" id=\"searchButton\"/>\n      <br/>\n      <input type=\"button\" value=\"Back to main page\" id=\"backButton\"/>\n      <br/>\n      <h3 id=\"response\"></h3>\n      <div></div>\n    </form>\n  </body>\n</html>\n" );
    }
  }
}


class $_scalate_$search_jade extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$search_jade.$_scalate_$render(context)
}
