/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package layout

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$welcome_jade {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val context: _root_.org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<html>\n  <head>\n    <title>my jade template</title>\n    <script type=\"text/javascript\" src=\"/assets/javascripts/addFeedback.js\"></script>\n  </head>\n  <body>\n    <input type=\"button\" value=\"Add\" id=\"renderAddButton\"/>\n    <br/>\n    <br/>\n    <form id=\"searchButtonForm\" method=\"GET\" action=\"/searchRenderer\">\n      <input type=\"submit\" value=\"Search\"/>\n    </form>\n    <form id=\"deleteButtonForm\" method=\"GET\" action=\"/deleteRenderer\">\n      <input type=\"submit\" value=\"Delete\"/>\n    </form>\n    <form id=\"updateButtonForm\" method=\"GET\" action=\"/updateRenderer\">\n      <input type=\"submit\" value=\"Update\"/>\n    </form>\n    <form id=\"viewButtonForm\" method=\"GET\" action=\"/veiwDB\">\n      <input type=\"submit\" value=\"View Data\"/>\n    </form>\n  </body>\n</html>\n" );
    }
  }
}


class $_scalate_$welcome_jade extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$welcome_jade.$_scalate_$render(context)
}
